<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Employees Manager</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js" type="text/javascript"></script>
</head>
<body>
<style>
    .mr-10 {
        margin-right: 10px;
        color: #333;
    }

    .mb-20 {
        margin-bottom: 20px;
    }
    label.error {
        color: red;
    }
    .sidebar-divine {
        height: 1px;
        background: hsla(0,0%,100%,.2);
        margin: 15px 11px;
    }
</style>
<div class="container">
    <div class="row">
        <!-- Page header -->
    </div>
    <div class="row">
        <div class="col-md-12">
            <nav class="navbar navbar-default">
                <div class="container-fluid">

                    <ul class="nav navbar-nav">

                        <?php

                        if (isset($_SESSION['adminid']) AND $_SESSION['adminid']>0)
                        {
                            if ($_SERVER['REQUEST_URI'] == "/?action=addpost")
                                echo "<li class='active'><a href='#'>Add entry</a></li>";
                            else
                                echo "<li><a href='/?action=addpost'>Add entry</a></li>";


                            echo "<li><a href='/logout'>Logout</a></li>";
                        }
                        ?>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <!-- Breadcrumbs -->
            <?php /* echo $this->pageBreadcrumbs()->render(); */ ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <!-- Page content placeholder -->
            <?= $this->content; ?>
        </div>
    </div>
    <hr>
</div>
<?php /* = $this->inlineScript() */ ?>
</body>
</html>