<h1>View Record</h1>
<div class="sidebar-divine"></div>
<?php
    $employee = isset($variables) ? $variables[0] : [];
?>
<?php if (!empty($_GET['success']) && $_GET['success'] == "false") { ?>
    <div class="alert alert-danger" role="alert">
        Đã xảy ra lỗi, vui lòng thử lại sau.
    </div>
<?php } ?>
<div class="row">
    
    <div class="col-6">
        <div class="mb-2 pb-50">
            <h6>ID</h6>
            <span><?= $employee->id ?></span>
        </div>
        <div class="mb-2 pb-50">
            <h6>Name</h6>
            <span><?= $employee->name ?></span>
        </div>
        <div class="mb-2 pb-50">
            <h6>Description</h6>
            <span><?= $employee->description ?></span>
        </div>
        <div class="mb-2 pb-50">
            <h6>Salary</h6>
            <span><?= number_format($employee->salary) ?> VNĐ</span>
        </div>
        <div class="mb-2 pb-50">
            <h6>Gender</h6>
            <span><?php echo $employee->gender == 1 ? "Female" : "Male" ?></span>
        </div>
        <div class="mb-2 pb-50">
            <h6>Birthday</h6>
            <span><?= $employee->birthday ?></span>
        </div>
        <div class="mb-2 pb-50">
            <h6>Created_at</h6>
            <span><?= $employee->created_at ?></span>
        </div>
    </div>
    <div class="col-12">
        <a class="btn btn-primary" href="/">
            Back
        </a>
    </div>
</div>